### PR TITLE
GitHub actions for running

### PR DESCRIPTION
**Pull request by th31nitiate**
This PR helps introduce methods for running eunit tests via GitHub actions. Their trigger by a push to any of branches. I have made a few changes which a described in the commit description. The description should provide an overview of the changes made to each of the files and basic reasoning behind some of those changes. 

More information can be found at the following issue description: #10

### CODE REVIEW

**Comment by choptastic** [comment]
Thanks for all the help with this.

I did a fair amount of reworking it so that it would test with several versions of OTP, PG, and MySQL (https://github.com/choptastic/sql_bridge/commit/4f0c78281a0053f3f4d021914f627bb3d0427a09), and run dialyzer. 

So now it's testing against OTP 24-26, PG 11-16, MySQL 5 and 8, and MariaDB 10-11 (https://github.com/choptastic/sql_bridge/actions/runs/6123871633)

And all the test are passing, except OTP 26 is throwing a pile of odd dialyzer errors (saying a bunch of built-in modules can't be found - probably a dumb config thing I need to review).

**Comment by choptastic** [comment]
Thanks again for all the help with this!

Finally passing all tests and dialyzer on OTP 26.

https://github.com/choptastic/sql_bridge/actions/runs/6132104325

**Comment by th31nitiate** [comment]
> Thanks again for all the help with this!
> 
> Finally passing all tests and dialyzer on OTP 26.
> 
> https://github.com/choptastic/sql_bridge/actions/runs/6132104325

Cool, I seen the dialyzer error and was not too sure how to handle them so I did not add that in. Though I like how dynamic the workflow files is looking.

Though I wonder how you felt getting to speed with actions, do you enjoy them & find them useful ?

The matrix feature and the includes seem pretty awesome. I was not aware of the marketplace actions but that seems to make the process much more refined & organized. Encase if you ever wish to expand this in the future.

**Comment by choptastic** [comment]
Getting some of those marketplace actions and the matrix all working as expected was a ton of trial and error (I think it ended up being around 50 commits that I ended up squashing).

The matrix feature on particular was very cool, but I had to be a bit more explicit with it than originally wanted to be, since the usual matrix function is fully multiplicative - so at one point, it was going to be doing like 75 different combinations (3 versions of erlang * 5 versions of mysql * 5 versions of postgres = 75 combinations).

So to prevent the wastefulness, I had 59 manually specify the combinations to test.

Overall, I really like it. I had done a lot with Travis-ci like 5 Years ago, but they stopped supporting open source. I had also tinkered with circle-ci a bit, and that was fine, but I think I do like the githuv actions best.

Thanks agqin for getting that started. I had looked briefly at gh actions a few months back and found myself confused, but the work you did to get something operational made something *click* and I was able to run with that.

One resource that really helped me work through the matrix stuff was looking at the github actions on the rebar3 repo.

**Comment by th31nitiate** [comment]
Yh, that's pretty cool, I take the same approach when learning by looking at other repo's like you did with the rebar3 repo.

Maybe in a week or two, though not a requirement as everyone pretty much works from the master branch. I would be able to look making this work with releases. That can be helpful in aiding with a bit of automation which may alleviate the maintenance burden for you.

**Pull request merged**
